Repository mozilla/telemetry-airflow, pull requests merged in 2024-03, with the labels that each got.

#1942 feat: Upgrade Python to 3.11.8 and remove trailing whitespaces
  .circleci/config.yml
  Dockerfile
  README.md
  constraints.txt
  requirements.in
  requirements.txt
Labels: dependencies

#1954 feat(DENG-2863): add data-observability-dev to the list of projects covered by artifact_deployment
  dags/bqetl_artifact_deployment.py
Labels: enhancement

#1955 fix: 1952 Acoustic Suppression List DENG 3082 date format
  dags/fivetran_acoustic.py
Labels: bug
